---
# tasks file for roles/omero-logmonitor

- name: system packages | install dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python-virtualenv

- name: omero logmonitor | setup virtualenv
  become: yes
  pip:
    name: slackclient
    state: present
    virtualenv: "{{ omero_logmonitor_venv }}"
    virtualenv_site_packages: yes

- name: omero logmonitor | create system user
  become: yes
  user:
    name: "{{ omero_logmonitor_system_user }}"
    home: "{{ omero_logmonitor_basedir }}"
    createhome: no
    state: present
    system: yes

- name: omero logmonitor | create logmonitor directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ omero_logmonitor_basedir }}"

- name: omero logmonitor | get logmonitor
  become: yes
  git:
    dest: "{{ omero_logmonitor_logbotdir }}"
    repo: https://github.com/openmicroscopy/omero-fenton.git
    version: "{{ omero_logmonitor_version }}"

- name: omero logmonitor | create configuration file
  become: yes
  template:
    src: omero-fenton-cfg.j2
    dest: "{{ omero_logmonitor_logbotdir }}/omero-fenton.cfg"
  notify:
    - restart logmonitor

- name: omero logmonitor | create systemd file
  become: yes
  template:
    dest: /etc/systemd/system/omero-logmonitor.service
    force: yes
    src: systemd-system-omero-logmonitor-service.j2
  notify:
    - restart logmonitor

- name: omero | enable logmonitor systemd
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: omero-logmonitor.service
    state: started
  when: omero_logmonitor_autostart

- name: omero | disable logmonitor systemd
  become: yes
  systemd:
    enabled: no
    name: omero-logmonitor.service
    state: stopped
  when: not omero_logmonitor_autostart
