---
# handlers file for roles/omero-logmonitor

- name: restart logmonitor
  become: yes
  systemd:
    daemon_reload: yes
    name: omero-logmonitor
    state: restarted
  when: omero_logmonitor_autostart
